[tool.poetry]
name = "raspberrypi-pio-poc"
version = "0.3.0"
description = "Proof of Concept"
authors = ["Nathan Young <nathan@::0/128>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
